# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true # default
contact_links:
  - name: Chat with devs
    url: https://gitter.im/QuantStack/Lobby
    about: Ask short questions about using voila
  - name: "\U0001F914 All other questions, including if you're not sure what to do."
    url: https://discourse.jupyter.org
    about: Search on Discourse for similar questions or ask for help there.
